### 1. Array

In [17]:
import numpy as np

t1 = np.array([1,2,3,])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
t2 = np.array(range(10))
print(t2)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
t3 = np.arange(4,10,2)
print(t3)
print(t3.dtype)
print(type(t3))

[4 6 8]
int32
<class 'numpy.ndarray'>


In [20]:
t4 = np.array(range(1,4), dtype=float)
print(t4)
print(t4.dtype)

[1. 2. 3.]
float64


In [22]:
t5 = np.array([1,1,0,1,0,0], dtype=bool)
print(t5)
print(t5.dtype)

[ True  True False  True False False]
bool


In [23]:
t6 = t5.astype("int8")
print(t6)
print(t6.dtype)

[1 1 0 1 0 0]
int8


In [27]:
import random
t7 = np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)

t8 = np.round(t7, 2)
print(t8)

[0.4757123  0.32304928 0.31567081 0.11265698 0.46611222 0.91094618
 0.95128961 0.03284702 0.62865437 0.06992712]
float64
[0.48 0.32 0.32 0.11 0.47 0.91 0.95 0.03 0.63 0.07]


In [31]:
print("%.2f"%random.random())
print("%.3f"%random.random())

0.37
0.359


### 2. Array Compute

In [34]:
import numpy as np
t1 = np.arange(12)
print(t1)
print(t1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [38]:
t2 = np.array([[1,2,3],[4,5,6]])
print(t2)
print(t2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [39]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
print(t3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [47]:
t4 = np.arange(12)
print(t4)
t4 = t4.reshape(3,4)
print(t4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
t5 = np.arange(24).reshape(2,3,4)
print(t5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [81]:
t5.reshape(4,6) # no mutation applied to itself

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [82]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
t5=t5.reshape(1,24)
print(t5)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


In [71]:
t5.shape[0]*t5.shape[1]

24

In [75]:
t6 = t5.reshape(t5.shape[0]*t5.shape[1],)
print(t6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [89]:
t5 = t5.reshape(4,6) 
print(t5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [92]:
t5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [96]:
t5+2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [97]:
t5/2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [99]:
t6 = np.arange(100, 124).reshape(4,6)

In [100]:
t6

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [101]:
t5+t6

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

### 3. Read file